name: deploy

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        corepack enable &&
        corepack install # use the in-repo yarn version
    - uses: actions/setup-node@v4
      with:
        cache: "yarn"

    - run: just build

    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'build'
    - uses: actions/deploy-pages@v4
